var settings = {
    "costFail": 10, 
    "ranks": "top", 
    "hardMode": 22.71, 
    "cooldownUser": 5.00, 
    "msgCurrency": "You do not have enough $currency ($points), $cost needed!", 
    "msgHelp": "/w $command generates a cipher, $start to start deciphering a cipher. $stats lists stats, $ranks lists top 3 crackers. $enable/$disable enables or disables random encounters. Extract the number sequence from the cipher to solve it.", 
    "help": "help", 
    "command": "!cipher", 
    "msgEncounter": "@$user you have generated a cipher, type [$start] to start decoding. Use [$help] to view instructions. [$time minute/s left]", 
    "cooldownRandom": 15.00, 
    "timerHard": 13, 
    "msgSolved": "Congratulations @$user! You have earned $points $currency by solving the cipher in $time seconds.", 
    "codeLengthHard": 9.00, 
    "claim": "N/A", 
    "msgEnabled": "/w you have enabled random cipher encounters, to disable them use [$disable]", 
    "msgRanks": "Cipher Leaderboard: $top", 
    "update": true, 
    "cooldownGlobal": 0.00, 
    "timerStart": 1, 
    "timer": 10, 
    "enable": "enable", 
    "disable": "disable", 
    "start": "!start", 
    "msgCooldown": "The generator is cooling down, try again in [$cooldown]!", 
    "msgFailed": "@$user you have failed to input the correct code ($code) in time ($time), good luck next time!", 
    "msgTimeout": "/w cipher timed-out after $time, try again in [$cooldown].", 
    "random": 12.32, 
    "cost": 10, 
    "stats": "stats", 
    "reward": 12, 
    "rewardHard": 24, 
    "codeLengthScramble": 24.00, 
    "codeLength": 6.00, 
    "msgStats": "/w Attempts: $attempts | Encounter: $encounter | Solved: $solved | Record: $record | Average: $average | Rate: $success", 
    "msgDisabled": "/w you have disabled random cipher encounters, to enable them again use [$enable]", 
    "blacklist": "HypeBot", 
    "msgStart": "@$user your cipher is [$cipher], extract the code from it. [$time seconds left]!"
}